general_settings:
  store_prompts_in_spend_logs: true
litellm_settings:
  cache: true
  cache_params:
    host: 10.10.1.1
    password: ''
    port: 6379
    type: redis
    ttl: 600
  drop_params: true
router_settings:
  routing_strategy: cost-based-routing
  redis_host: 10.10.1.1
  redis_password: ''
  redis_port: 6379
model_list:
- model_name: arcee-auto
  litellm_params:
    model: openai/auto
    api_base: https://conductor.arcee.ai/v1
    api_key: os.environ/ARCEE_API_KEY
- litellm_params:
    api_base: os.environ/AZURE_API_BASE
    api_key: os.environ/AZURE_API_KEY
    model: azure/dall-e-3
  model_name: az-dall-e-3
  model_info:
    mode: image_generation
- litellm_params:
    api_base: os.environ/AZURE_API_BASE_EastUS2
    api_key: os.environ/AZURE_API_KEY_EastUS2
    model: azure/model-router
  model_name: az-model-router
- litellm_params:
    api_base: os.environ/AZURE_API_BASE
    api_key: os.environ/AZURE_API_KEY
    model: azure_ai/Phi-4-mini-instruct
    input_cost_per_token: 7.5e-08
    output_cost_per_token: 3e-7
  model_name: az-phi-4-mini-instruct
- litellm_params:
    model: novita/deepseek/deepseek-r1-0528-qwen3-8b
    input_cost_per_token: 6.0e-08
    output_cost_per_token: 9.0e-08
  model_name: deepseek-r1-0528-qwen3-8b
- litellm_params:
    model: openrouter/deepseek/deepseek-r1-0528-qwen3-8b
    input_cost_per_token: 1.0e-08
    output_cost_per_token: 2.0e-08
  model_name: deepseek-r1-0528-qwen3-8b
- litellm_params:
    model: openrouter/deepseek/deepseek-r1-0528-qwen3-8b:free
    input_cost_per_token: 1.0e-09
    output_cost_per_token: 1.0e-09
  model_name: deepseek-r1-0528-qwen3-8b
- litellm_params:
    model: novita/baidu/ernie-4.5-21B-a3b
    input_cost_per_token: 1.0e-09
    output_cost_per_token: 1.0e-09
  model_name: ernie-4.5-21B-a3b-free
- model_name: gemini-2.5-flash
  litellm_params:
    model: gemini/gemini-2.5-flash
    api_key: os.environ/GEMINI_API_KEY
    input_cost_per_token: 1.0e-09
    output_cost_per_token: 1.0e-09
- litellm_params:
    model: openai/coding/gemini-2.5-flash
    input_cost_per_token: 3.0e-07
    output_cost_per_token: 2.5e-06
    api_base: https://router.requesty.ai/v1
    api_key: os.environ/REQUESTY_API_KEY
  model_name: gemini-2.5-flash
- litellm_params:
    model: openrouter/google/gemini-2.5-flash
    input_cost_per_token: 3.0e-07
    output_cost_per_token: 2.5e-06
  model_name: gemini-2.5-flash
- model_name: gemini-2.5-flash-lite
  litellm_params:
    model: gemini/gemini-2.5-flash-lite
    api_key: os.environ/GEMINI_API_KEY
    input_cost_per_token: 1.0e-09
    output_cost_per_token: 1.0e-09
- litellm_params:
    model: openai/google/gemini-2.5-flash-lite-preview-06-17
    input_cost_per_token: 1.0e-07
    output_cost_per_token: 4.0e-07
    api_base: https://router.requesty.ai/v1
    api_key: os.environ/REQUESTY_API_KEY
  model_name: gemini-2.5-flash-lite
- litellm_params:
    model: openrouter/google/gemini-2.5-flash-lite
    input_cost_per_token: 1.0e-07
    output_cost_per_token: 4.0e-07
  model_name: gemini-2.5-flash-lite
- model_name: gemini-2.5-pro
  litellm_params:
    model: gemini/gemini-2.5-pro
    api_key: os.environ/GEMINI_API_KEY
    input_cost_per_token: 1.0e-09
    output_cost_per_token: 1.0e-09
- model_name: gemini-2.5-pro
  litellm_params:
    model: openai/coding/gemini-2.5-pro
    input_cost_per_token: 1.25e-06
    output_cost_per_token: 1.0e-05
    api_base: https://router.requesty.ai/v1
    api_key: os.environ/REQUESTY_API_KEY
- litellm_params:
    model: openrouter/google/gemini-2.5-pro
    input_cost_per_token: 1.25e-06
    output_cost_per_token: 1.0e-05
  model_name: gemini-2.5-pro
- model_name: gemini-embedding-001
  litellm_params:
    model: gemini/gemini-embedding-001
    api_key: os.environ/GEMINI_API_KEY
    input_cost_per_token: 1.0e-09
    output_cost_per_token: 1.0e-09
  model_info:
    mode: embedding
- model_name: gemma-3-27b-free
  litellm_params:
    model: gemini/gemma-3-27b-it
    api_key: os.environ/GEMINI_API_KEY
    input_cost_per_token: 1.0e-09
    output_cost_per_token: 1.0e-09
- litellm_params:
    model: openrouter/google/gemma-3-27b-it:free
    input_cost_per_token: 1.0e-09
    output_cost_per_token: 1.0e-09
  model_name: gemma-3-27b-free
- model_name: gpt-4.1
  litellm_params:
    model: openai/gpt-4.1
    api_key: os.environ/OPENAI_API_KEY
- model_name: gpt-4.1-mini
  litellm_params:
    model: openai/gpt-4.1-mini
    api_key: os.environ/OPENAI_API_KEY
- model_name: jina-embeddings-v4
  litellm_params:
    model: jina_ai/jina-embeddings-v4
    api_key: os.environ/JINA_AI_API_KEY
  model_info:
    mode: embedding
- model_name: jina-reranker-m0
  litellm_params:
    model: jina_ai/jina-reranker-m0
    api_key: os.environ/JINA_AI_API_KEY
  model_info:
    mode: rerank
- litellm_params:
    model: openai/anthropic/claude-3.5-haiku
    input_cost_per_token: 8.0e-07
    output_cost_per_token: 4.0e-06
    api_base: os.environ/KILOCODE_API_BASE
    api_key: os.environ/KILOCODE_API_KEY
  model_name: kc-claude-3.5-haiku
- model_name: nomic-embed-text
  litellm_params:
    model: infinity/nomic-ai/nomic-embed-text-v2-moe
    api_base: http://infinity:7997
  model_info:
    mode: embedding
- model_name: o4-mini
  litellm_params:
    model: openai/o4-mini
    api_key: os.environ/OPENAI_API_KEY
- model_name: oai-text-embedding-3-small
  litellm_params:
    model: openai/oai-text-embedding-3-small
    api_key: os.environ/OPENAI_API_KEY
  model_info:
    mode: embedding
- litellm_params:
    model: openrouter/anthropic/claude-3.5-haiku
    input_cost_per_token: 8.0e-07
    output_cost_per_token: 4.0e-06
  model_name: or-claude-3.5-haiku
- litellm_params:
    model: openrouter/anthropic/claude-3.7-sonnet
    input_cost_per_token: 3.0e-06
    output_cost_per_token: 1.5e-05
  model_name: or-claude-3.7-sonnet
- litellm_params:
    model: openrouter/anthropic/claude-opus-4
    input_cost_per_token: 1.5e-05
    output_cost_per_token: 7.5e-05
  model_name: or-claude-opus-4
- litellm_params:
    model: openrouter/anthropic/claude-sonnet-4
    input_cost_per_token: 3.0e-06
    output_cost_per_token: 1.5e-05
  model_name: or-claude-sonnet-4
- litellm_params:
    model: openrouter/mistralai/devstral-medium
    input_cost_per_token: 4.0e-07
    output_cost_per_token: 2.0e-06
  model_name: or-devstral-medium
- litellm_params:
    model: openrouter/mistralai/devstral-small
    input_cost_per_token: 7.0e-08
    output_cost_per_token: 2.8e-07
  model_name: or-devstral-small
- litellm_params:
    model: openrouter/mistralai/devstral-small-2505:free
    input_cost_per_token: 1.0e-09
    output_cost_per_token: 1.0e-09
  model_name: or-devstral-small-2505-free
- litellm_params:
    model: openrouter/meta-llama/llama-3.2-3b-instruct
    input_cost_per_token: 3.0e-09
    output_cost_per_token: 6.0e-09
  model_name: or-llama-3.2-3b-instruct
- litellm_params:
    model: openrouter/meta-llama/llama-3.2-3b-instruct:free
    input_cost_per_token: 1.0e-09
    output_cost_per_token: 1.0e-09
  model_name: or-llama-3.2-3b-instruct
- litellm_params:
    model: openrouter/meta-llama/llama-3.3-70b-instruct:free
    input_cost_per_token: 1.0e-09
    output_cost_per_token: 1.0e-09
  model_name: or-llama-3.3-70b-instruct-free
- litellm_params:
    model: openrouter/nvidia/llama-3.3-nemotron-super-49b-v1
    input_cost_per_token: 1.3e-07
    output_cost_per_token: 4.0e-07
  model_name: or-llama-3.3-nemotron-super-49b
- litellm_params:
    model: openrouter/mistralai/mistral-small-3.2-24b-instruct
    input_cost_per_token: 5.0e-08
    output_cost_per_token: 1.0e-07
  model_name: or-mistral-small-3.2-24b
- litellm_params:
    model: openrouter/mistralai/mistral-small-3.2-24b-instruct:free
    input_cost_per_token: 1.0e-09
    output_cost_per_token: 1.0e-09
  model_name: or-mistral-small-3.2-24b
- litellm_params:
    model: openrouter/moonshotai/kimi-k2
    input_cost_per_token: 8.78e-08
    output_cost_per_token: 8.78e-08
  model_name: or-moonshotai-kimi-k2
- litellm_params:
    model: openrouter/moonshotai/kimi-k2:free
    input_cost_per_token: 1.0e-09
    output_cost_per_token: 1.0e-09
  model_name: or-moonshotai-kimi-k2
- litellm_params:
    model: openrouter/openrouter/horizon-alpha
    input_cost_per_token: 1.0e-09
    output_cost_per_token: 1.0e-09
  model_name: or-openrouter-horizon-alpha
- litellm_params:
    model: openrouter/openrouter/horizon-beta
    input_cost_per_token: 1.0e-09
    output_cost_per_token: 1.0e-09
  model_name: or-openrouter-horizon-beta
- litellm_params:
    model: openrouter/qwen/qwen3-14b
    input_cost_per_token: 6.0e-08
    output_cost_per_token: 2.4e-07
  model_name: or-qwen3-14b
- litellm_params:
    model: openrouter/qwen/qwen3-14b:free
    input_cost_per_token: 1.0e-09
    output_cost_per_token: 1.0e-09
  model_name: or-qwen3-14b
- litellm_params:
    model: openrouter/qwen/qwen3-235b-a22b-2507
    input_cost_per_token: 1.179e-07
    output_cost_per_token: 1.179e-07
  model_name: or-qwen3-235b-a22b-2507
- litellm_params:
    model: openrouter/qwen/qwen3-30b-a3b
    input_cost_per_token: 8.0e-08
    output_cost_per_token: 2.9e-07
  model_name: or-qwen3-30b-a3b
- litellm_params:
    model: openrouter/qwen/qwen3-30b-a3b:free
    input_cost_per_token: 1.0e-09
    output_cost_per_token: 1.0e-09
  model_name: or-qwen3-30b-a3b
- litellm_params:
    model: openrouter/qwen/qwen3-32b
    input_cost_per_token: 2.7e-08
    output_cost_per_token: 2.7e-08
  model_name: or-qwen3-32b
- litellm_params:
    model: openrouter/qwen/qwen3-coder
    input_cost_per_token: 3.0e-07
    output_cost_per_token: 1.2e-06
  model_name: or-qwen3-coder
- litellm_params:
    model: openrouter/qwen/qwen3-coder:free
    input_cost_per_token: 1.0e-09
    output_cost_per_token: 1.0e-09
  model_name: or-qwen3-coder
- litellm_params:
    model: openrouter/z-ai/glm-4.5-air
    input_cost_per_token: 1.9e-07
    output_cost_per_token: 1.1e-06
  model_name: or-z-ai-glm-4.5-air
- litellm_params:
    model: openrouter/z-ai/glm-4.5-air:free
    input_cost_per_token: 1.0e-09
    output_cost_per_token: 1.0e-09
  model_name: or-z-ai-glm-4.5-air
- litellm_params:
    model: perplexity/r1-1776
    input_cost_per_token: 2.0e-06
    output_cost_per_token: 8.0e-06
  model_name: pplx-r1-1776
- litellm_params:
    model: perplexity/sonar
    input_cost_per_token: 1.0e-06
    output_cost_per_token: 1.0e-06
  model_name: pplx-sonar
- litellm_params:
    model: perplexity/sonar-pro
    input_cost_per_token: 3.0e-06
    output_cost_per_token: 1.5e-05
  model_name: pplx-sonar-pro
- model_name: req-smart-task
  litellm_params:
    model: openai/smart-task
    api_base: https://router.requesty.ai/v1
    api_key: os.environ/REQUESTY_API_KEY
- litellm_params:
    api_key: os.environ/TOGETHERAI_API_KEY
    model: together_ai/deepseek-ai/DeepSeek-R1-Distill-Llama-70B-free
    input_cost_per_token: 1.0e-09
    output_cost_per_token: 1.0e-09
  model_name: tgt-DeepSeek-R1-Distill-Llama-70B-free
- model_name: tgt-Salesforce-Llama-Rank-V1
  litellm_params:
    model: together_ai/Salesforce/Llama-Rank-V1
    api_key: os.environ/TOGETHERAI_API_KEY
  model_info:
    mode: rerank
