general_settings:
  store_prompts_in_spend_logs: true
litellm_settings:
  cache: true
  cache_params:
    host: 10.10.1.1
    password: ''
    port: 6379
    type: redis
    ttl: 600
  drop_params: true
router_settings:
  routing_strategy: cost-based-routing
  redis_host: 10.10.1.1
  redis_password: ''
  redis_port: 6379
model_list:
- model_name: arcee-auto
  litellm_params:
    model: openai/auto
    api_base: https://conductor.arcee.ai/v1
    api_key: os.environ/ARCEE_API_KEY
- litellm_params:
    api_base: os.environ/AZURE_API_BASE
    api_key: os.environ/AZURE_API_KEY
    model: azure/dall-e-3
  model_name: az-dall-e-3
  model_info:
    mode: image_generation
- litellm_params:
    api_base: os.environ/AZURE_API_BASE_EastUS2
    api_key: os.environ/AZURE_API_KEY_EastUS2
    model: azure/model-router
  model_name: az-model-router
- litellm_params:
    api_base: os.environ/AZURE_API_BASE
    api_key: os.environ/AZURE_API_KEY
    model: azure_ai/Phi-4-mini-instruct
    input_cost_per_token: 7.5e-08
    output_cost_per_token: 3e-7
  model_name: az-phi-4-mini-instruct
- model_name: claude-3-5-haiku
  litellm_params:
    model: openai/anthropic/claude-3-5-haiku-latest
    api_base: https://router.requesty.ai/v1
    api_key: os.environ/REQUESTY_API_KEY
    input_cost_per_token: 8.0e-07
    output_cost_per_token: 4.0e-06
- litellm_params:
    model: openrouter/anthropic/claude-3.5-haiku
    input_cost_per_token: 8.0e-07
    output_cost_per_token: 4.0e-06
  model_name: claude-3-5-haiku
- model_name: claude-3-7-sonnet
  litellm_params:
    model: openai/anthropic/claude-3-7-sonnet-latest
    api_base: https://router.requesty.ai/v1
    api_key: os.environ/REQUESTY_API_KEY
    input_cost_per_token: 3.0e-06
    output_cost_per_token: 1.5e-05
- litellm_params:
    model: openrouter/anthropic/claude-3.7-sonnet
    input_cost_per_token: 3.0e-06
    output_cost_per_token: 1.5e-05
  model_name: claude-3-7-sonnet
- model_name: claude-opus-4-1
  litellm_params:
    model: openai/anthropic/claude-opus-4-1-20250805
    api_base: https://router.requesty.ai/v1
    api_key: os.environ/REQUESTY_API_KEY
    input_cost_per_token: 1.5e-05
    output_cost_per_token: 7.5e-05
- litellm_params:
    model: openrouter/anthropic/claude-opus-4.1
    input_cost_per_token: 1.5e-05
    output_cost_per_token: 7.5e-05
  model_name: claude-opus-4-1
- model_name: claude-sonnet-4
  litellm_params:
    model: openai/anthropic/claude-sonnet-4-20250514-1m
    api_base: https://router.requesty.ai/v1
    api_key: os.environ/REQUESTY_API_KEY
    input_cost_per_token: 3.0e-06
    output_cost_per_token: 1.5e-05
- litellm_params:
    model: openrouter/anthropic/claude-sonnet-4
    input_cost_per_token: 3.0e-06
    output_cost_per_token: 1.5e-05
  model_name: claude-sonnet-4
- litellm_params:
    model: openai/anthropic/claude-sonnet-4-5-20250929
    api_base: https://router.requesty.ai/v1
    api_key: os.environ/REQUESTY_API_KEY
    input_cost_per_token: 3.0e-06
    output_cost_per_token: 1.5e-05
  model_name: claude-sonnet-4.5
- litellm_params:
    model: openrouter/anthropic/claude-sonnet-4.5
    input_cost_per_token: 3.0e-06
    output_cost_per_token: 1.5e-05
  model_name: claude-sonnet-4.5
- litellm_params:
    model: openrouter/deepseek/deepseek-r1-0528-qwen3-8b
    input_cost_per_token: 1.3043472e-08
    output_cost_per_token: 5.21739072e-08
  model_name: deepseek-r1-0528-qwen3-8b
- litellm_params:
    model: openrouter/deepseek/deepseek-r1-0528-qwen3-8b:free
    input_cost_per_token: 1.0e-09
    output_cost_per_token: 1.0e-09
  model_name: deepseek-r1-0528-qwen3-8b
- model_name: gemini-2.5-flash
  litellm_params:
    model: gemini/gemini-flash-latest
    api_key: os.environ/GEMINI_API_KEY
    input_cost_per_token: 1.0e-09
    output_cost_per_token: 1.0e-09
- litellm_params:
    model: openai/google/gemini-2.5-flash
    input_cost_per_token: 3.0e-07
    output_cost_per_token: 2.5e-06
    api_base: https://router.requesty.ai/v1
    api_key: os.environ/REQUESTY_API_KEY
  model_name: gemini-2.5-flash
- litellm_params:
    model: openrouter/google/gemini-2.5-flash-preview-09-2025
    input_cost_per_token: 3.0e-07
    output_cost_per_token: 2.5e-06
  model_name: gemini-2.5-flash
- model_name: gemini-2.5-flash-lite
  litellm_params:
    model: gemini/gemini-flash-lite-latest
    api_key: os.environ/GEMINI_API_KEY
    input_cost_per_token: 1.0e-09
    output_cost_per_token: 1.0e-09
- litellm_params:
    model: openai/google/gemini-2.5-flash-lite-preview-06-17
    input_cost_per_token: 1.0e-07
    output_cost_per_token: 4.0e-07
    api_base: https://router.requesty.ai/v1
    api_key: os.environ/REQUESTY_API_KEY
  model_name: gemini-2.5-flash-lite
- litellm_params:
    model: openrouter/google/gemini-2.5-flash-lite-preview-09-2025
    input_cost_per_token: 1.0e-07
    output_cost_per_token: 4.0e-07
  model_name: gemini-2.5-flash-lite
- model_name: gemini-2.5-pro
  litellm_params:
    model: gemini/gemini-2.5-pro
    api_key: os.environ/GEMINI_API_KEY
    input_cost_per_token: 1.0e-09
    output_cost_per_token: 1.0e-09
- model_name: gemini-2.5-pro
  litellm_params:
    model: openai/google/gemini-2.5-pro
    input_cost_per_token: 1.25e-06
    output_cost_per_token: 1.0e-05
    api_base: https://router.requesty.ai/v1
    api_key: os.environ/REQUESTY_API_KEY
- litellm_params:
    model: openrouter/google/gemini-2.5-pro
    input_cost_per_token: 1.25e-06
    output_cost_per_token: 1.0e-05
  model_name: gemini-2.5-pro
- model_name: gemini-embedding-001
  litellm_params:
    model: gemini/gemini-embedding-001
    api_key: os.environ/GEMINI_API_KEY
    input_cost_per_token: 1.0e-09
    output_cost_per_token: 1.0e-09
  model_info:
    mode: embedding
- model_name: gemma-3-27b-free
  litellm_params:
    model: gemini/gemma-3-27b-it
    api_key: os.environ/GEMINI_API_KEY
    input_cost_per_token: 1.0e-09
    output_cost_per_token: 1.0e-09
- litellm_params:
    model: openrouter/google/gemma-3-27b-it:free
    input_cost_per_token: 1.0e-09
    output_cost_per_token: 1.0e-09
  model_name: gemma-3-27b-free
- model_name: gpt-4.1
  litellm_params:
    model: openai/gpt-4.1
    api_key: os.environ/OPENAI_API_KEY
- model_name: gpt-4.1-mini
  litellm_params:
    model: openai/gpt-4.1-mini
    api_key: os.environ/OPENAI_API_KEY
- litellm_params:
    api_base: os.environ/AZURE_API_BASE_EastUS2
    api_key: os.environ/AZURE_API_KEY_EastUS2
    model: azure/gpt-4.1-nano
    input_cost_per_token: 1.0e-07
    output_cost_per_token: 4.0e-07
  model_name: gpt-4.1-nano
- model_name: gpt-4.1-nano
  litellm_params:
    model: openai/gpt-4.1-nano
    api_key: os.environ/OPENAI_API_KEY
- model_name: gpt-5
  litellm_params:
    model: openai/gpt-5
    api_key: os.environ/OPENAI_API_KEY
- model_name: gpt-5-codex
  litellm_params:
    model: openai/gpt-5-codex
    api_key: os.environ/OPENAI_API_KEY
- litellm_params:
    api_base: os.environ/AZURE_API_BASE_EastUS2
    api_key: os.environ/AZURE_API_KEY_EastUS2
    model: azure/gpt-5-mini
    input_cost_per_token: 2.5e-07
    output_cost_per_token: 2.0e-06
  model_name: gpt-5-mini
- model_name: gpt-5-mini
  litellm_params:
    model: openai/gpt-5-mini
    api_key: os.environ/OPENAI_API_KEY
- litellm_params:
    api_base: os.environ/AZURE_API_BASE_EastUS2
    api_key: os.environ/AZURE_API_KEY_EastUS2
    model: azure/gpt-5-nano
    input_cost_per_token: 5.0e-08
    output_cost_per_token: 4.0e-07
  model_name: gpt-5-nano
- model_name: gpt-5-nano
  litellm_params:
    model: openai/gpt-5-nano
    api_key: os.environ/OPENAI_API_KEY
- litellm_params:
    model: openrouter/openai/gpt-oss-120b
    input_cost_per_token: 7.2e-08
    output_cost_per_token: 2.8e-07
  model_name: gpt-oss-120b
- model_name: gpt-oss-120b
  litellm_params:
    model: vercel_ai_gateway/openai/gpt-oss-120b
    input_cost_per_token: 1.0e-07
    output_cost_per_token: 5.0e-07
- litellm_params:
    model: openrouter/openai/gpt-oss-20b
    input_cost_per_token: 4.0e-08
    output_cost_per_token: 1.5e-07
  model_name: gpt-oss-20b
- model_name: gpt-oss-20b
  litellm_params:
    model: vercel_ai_gateway/openai/gpt-oss-20b
    input_cost_per_token: 7.0e-08
    output_cost_per_token: 3.0e-07
- model_name: jina-embeddings-v4
  litellm_params:
    model: jina_ai/jina-embeddings-v4
    api_key: os.environ/JINA_AI_API_KEY
  model_info:
    mode: embedding
- model_name: jina-reranker-m0
  litellm_params:
    model: jina_ai/jina-reranker-m0
    api_key: os.environ/JINA_AI_API_KEY
  model_info:
    mode: rerank
- litellm_params:
    model: openai/anthropic/claude-3.5-haiku
    input_cost_per_token: 8.0e-07
    output_cost_per_token: 4.0e-06
    api_base: os.environ/KILOCODE_API_BASE
    api_key: os.environ/KILOCODE_API_KEY
  model_name: kc-claude-3.5-haiku
- model_name: nomic-embed-text
  litellm_params:
    model: infinity/nomic-ai/nomic-embed-text-v2-moe
    api_base: http://infinity:7997
  model_info:
    mode: embedding
- litellm_params:
    model: openrouter/nvidia/nemotron-nano-9b-v2
    input_cost_per_token: 4.0e-08
    output_cost_per_token: 1.6e-07
  model_name: nvidia-nemotron-nano-9b-v2
- litellm_params:
    model: openrouter/nvidia/nemotron-nano-9b-v2:free
    input_cost_per_token: 1.0e-09
    output_cost_per_token: 1.0e-09
  model_name: nvidia-nemotron-nano-9b-v2
- model_name: oai-text-embedding-3-small
  litellm_params:
    model: openai/oai-text-embedding-3-small
    api_key: os.environ/OPENAI_API_KEY
  model_info:
    mode: embedding
- litellm_params:
    model: openrouter/deepseek/deepseek-v3.1-terminus
    input_cost_per_token: 2.7e-07
    output_cost_per_token: 1.0e-06
  model_name: or-deepseek-v3.1-terminus
- model_name: or-deepseek-v3.2-exp
  litellm_params:
    model: openrouter/deepseek/deepseek-v3.2-exp
    input_cost_per_token: 2.8e-07
    output_cost_per_token: 4.2e-07
- litellm_params:
    model: openrouter/mistralai/devstral-medium
    input_cost_per_token: 4.0e-07
    output_cost_per_token: 2.0e-06
  model_name: or-devstral-medium
- litellm_params:
    model: openrouter/mistralai/devstral-small
    input_cost_per_token: 7.0e-08
    output_cost_per_token: 2.8e-07
  model_name: or-devstral-small
- litellm_params:
    model: openrouter/google/gemini-2.5-flash-image-preview
    input_cost_per_token: 3.0e-07
    output_cost_per_token: 2.5e-06
  model_name: or-gemini-2.5-flash-image-preview
- litellm_params:
    model: openrouter/meta-llama/llama-3.2-3b-instruct
    input_cost_per_token: 1.2e-08
    output_cost_per_token: 2.4e-08
  model_name: or-llama-3.2-3b-instruct
- litellm_params:
    model: openrouter/meta-llama/llama-3.2-3b-instruct:free
    input_cost_per_token: 1.0e-09
    output_cost_per_token: 1.0e-09
  model_name: or-llama-3.2-3b-instruct
- litellm_params:
    model: openrouter/meta-llama/llama-3.3-70b-instruct:free
    input_cost_per_token: 1.0e-09
    output_cost_per_token: 1.0e-09
  model_name: or-llama-3.3-70b-instruct-free
- litellm_params:
    model: openrouter/meta-llama/llama-3.3-8b-instruct:free
    input_cost_per_token: 1.0e-09
    output_cost_per_token: 1.0e-09
  model_name: or-llama-3.3-8b-instruct-free
- litellm_params:
    model: openrouter/mistralai/codestral-2508
    input_cost_per_token: 3.0e-07
    output_cost_per_token: 9.0e-07
  model_name: or-mistral-codestral-2508
- litellm_params:
    model: openrouter/mistralai/mistral-medium-3.1
    input_cost_per_token: 4.0e-07
    output_cost_per_token: 2.0e-06
  model_name: or-mistral-mistral-medium-3.1
- litellm_params:
    model: openrouter/mistralai/mistral-small-3.2-24b-instruct
    input_cost_per_token: 5.0e-08
    output_cost_per_token: 1.0e-07
  model_name: or-mistral-small-3.2-24b
- litellm_params:
    model: openrouter/moonshotai/kimi-k2-0905
    input_cost_per_token: 3.804346e-07
    output_cost_per_token: 1.52173896e-06
  model_name: or-moonshotai-kimi-k2-0905
- litellm_params:
    model: openrouter/nvidia/llama-3.3-nemotron-super-49b-v1.5
    input_cost_per_token: 1.0e-07
    output_cost_per_token: 4.0e-07
  model_name: or-nvidia-llama-3.3-nemotron-super-49b-v1.5
- litellm_params:
    model: openrouter/openai/gpt-5-chat
    input_cost_per_token: 1.25e-06
    output_cost_per_token: 1.0e-05
  model_name: or-openai-gpt-5-chat
- litellm_params:
    model: openrouter/opengvlab/internvl3-78b
    input_cost_per_token: 3.0e-08
    output_cost_per_token: 1.3e-07
  model_name: or-opengvlab-internvl3-78b
- model_name: or-qwen-plus-2025-07-28
  litellm_params:
    model: openrouter/qwen/qwen-plus-2025-07-28
    input_cost_per_token: 4.0e-07
    output_cost_per_token: 1.2e-06
- model_name: or-qwen-plus-2025-07-28-thinking
  litellm_params:
    model: openrouter/qwen/qwen-plus-2025-07-28:thinking
    input_cost_per_token: 4.0e-07
    output_cost_per_token: 4.0e-06
- litellm_params:
    model: openrouter/qwen/qwen3-235b-a22b-2507
    input_cost_per_token: 9.74999532e-08
    output_cost_per_token: 3.8999995632e-07
  model_name: or-qwen3-235b-a22b-2507
- litellm_params:
    model: openrouter/qwen/qwen3-30b-a3b-instruct-2507
    input_cost_per_token: 7.065214e-08
    output_cost_per_token: 2.82608664e-07
  model_name: or-qwen3-30b-a3b-2507
- litellm_params:
    model: openrouter/qwen/qwen3-30b-a3b-thinking-2507
    input_cost_per_token: 8.967387e-08
    output_cost_per_token: 3.58695612e-07
  model_name: or-qwen3-30b-a3b-thinking-2507
- litellm_params:
    model: openrouter/qwen/qwen3-coder
    input_cost_per_token: 2.4999988e-07
    output_cost_per_token: 9.99999888e-07
  model_name: or-qwen3-coder
- litellm_params:
    model: openrouter/qwen/qwen3-coder-30b-a3b-instruct
    input_cost_per_token: 7.065214e-08
    output_cost_per_token: 2.82608664e-07
  model_name: or-qwen3-coder-30b-a3b-instruct
- litellm_params:
    model: openrouter/qwen/qwen3-vl-235b-a22b-instruct
    input_cost_per_token: 3.0e-07
    output_cost_per_token: 1.5e-06
  model_name: or-qwen3-vl-235b-a22b-instruct
- litellm_params:
    model: openrouter/qwen/qwen3-vl-235b-a22b-thinking
    input_cost_per_token: 3.0e-07
    output_cost_per_token: 3.0e-06
  model_name: or-qwen3-vl-235b-a22b-thinking
- litellm_params:
    model: perplexity/sonar
    input_cost_per_token: 1.0e-06
    output_cost_per_token: 1.0e-06
  model_name: pplx-sonar
- litellm_params:
    model: perplexity/sonar-pro
    input_cost_per_token: 3.0e-06
    output_cost_per_token: 1.5e-05
  model_name: pplx-sonar-pro
- model_name: qwen3-coder-flash
  litellm_params:
    model: openai/qwen/qwen3-coder-flash
    api_base: os.environ/NANOGPT_API_BASE
    api_key: os.environ/NANOGPT_API_KEY
    input_cost_per_token: 3.0e-07
    output_cost_per_token: 1.5e-06
- litellm_params:
    model: openrouter/qwen/qwen3-coder-flash
    input_cost_per_token: 3.0e-07
    output_cost_per_token: 1.5e-06
  model_name: qwen3-coder-flash
- model_name: qwen3-coder-plus
  litellm_params:
    model: openai/qwen/qwen3-coder-plus
    api_base: os.environ/NANOGPT_API_BASE
    api_key: os.environ/NANOGPT_API_KEY
    input_cost_per_token: 1.0e-06
    output_cost_per_token: 5.0e-06
- litellm_params:
    model: openrouter/qwen/qwen3-coder-plus
    input_cost_per_token: 1.0e-06
    output_cost_per_token: 5.0e-06
  model_name: qwen3-coder-plus
- model_name: qwen3-coder-plus
  litellm_params:
    model: vercel_ai_gateway/alibaba/qwen3-coder-plus
    input_cost_per_token: 1.0e-06
    output_cost_per_token: 5.0e-06
- model_name: qwen3-max
  litellm_params:
    model: openai/qwen/qwen3-max
    api_base: os.environ/NANOGPT_API_BASE
    api_key: os.environ/NANOGPT_API_KEY
    input_cost_per_token: 1.2e-06
    output_cost_per_token: 6.0e-06
- model_name: qwen3-max
  litellm_params:
    model: openrouter/qwen/qwen3-max
    input_cost_per_token: 1.2e-06
    output_cost_per_token: 6.0e-06
- litellm_params:
    model: openrouter/qwen/qwen3-next-80b-a3b-instruct
    input_cost_per_token: 9.782604e-08
    output_cost_per_token: 3.91304304e-07
  model_name: qwen3-next-80b-a3b-instruct
- model_name: qwen3-next-80b-a3b-instruct
  litellm_params:
    model: vercel_ai_gateway/alibaba/qwen3-next-80b-a3b-instruct
    input_cost_per_token: 1.5e-07
    output_cost_per_token: 1.5e-06
- litellm_params:
    model: openrouter/qwen/qwen3-next-80b-a3b-thinking
    input_cost_per_token: 9.782604e-08
    output_cost_per_token: 3.91304304e-07
  model_name: qwen3-next-80b-a3b-thinking
- model_name: qwen3-next-80b-a3b-thinking
  litellm_params:
    model: vercel_ai_gateway/alibaba/qwen3-next-80b-a3b-thinking
    input_cost_per_token: 1.4e-07
    output_cost_per_token: 1.4e-06
- model_name: req-smart-task
  litellm_params:
    model: openai/smart-task
    api_base: https://router.requesty.ai/v1
    api_key: os.environ/REQUESTY_API_KEY
- litellm_params:
    api_key: os.environ/TOGETHERAI_API_KEY
    model: together_ai/deepseek-ai/DeepSeek-R1-Distill-Llama-70B-free
    input_cost_per_token: 1.0e-09
    output_cost_per_token: 1.0e-09
  model_name: tgt-DeepSeek-R1-Distill-Llama-70B-free
- model_name: tgt-Salesforce-Llama-Rank-V1
  litellm_params:
    model: together_ai/Salesforce/Llama-Rank-V1
    api_key: os.environ/TOGETHERAI_API_KEY
  model_info:
    mode: rerank
- model_name: vc-meituan-longcat-flash-chat
  litellm_params:
    model: vercel_ai_gateway/meituan/longcat-flash-chat
    input_cost_per_token: 1.0e-09
    output_cost_per_token: 1.0e-09
- model_name: x-ai-grok-code-fast-1
  litellm_params:
    model: openai/x-ai/grok-code-fast-1
    api_base: os.environ/NANOGPT_API_BASE
    api_key: os.environ/NANOGPT_API_KEY
    input_cost_per_token: 2.0e-07
    output_cost_per_token: 1.5e-06
- litellm_params:
    model: openrouter/x-ai/grok-code-fast-1
    input_cost_per_token: 2.0e-07
    output_cost_per_token: 1.5e-06
  model_name: x-ai-grok-code-fast-1
- litellm_params:
    model: openrouter/z-ai/glm-4.5-air
    input_cost_per_token: 1.4e-07
    output_cost_per_token: 8.6e-07
  model_name: zai-glm-4.5-air
- litellm_params:
    model: openrouter/z-ai/glm-4.5-air:free
    input_cost_per_token: 1.0e-09
    output_cost_per_token: 1.0e-09
  model_name: zai-glm-4.5-air
- model_name: zai-glm-4.5-air
  litellm_params:
    model: vercel_ai_gateway/zai/glm-4.5-air
    input_cost_per_token: 2.0e-07
    output_cost_per_token: 1.1e-06
- model_name: zai-glm-4.5v
  litellm_params:
    model: vercel_ai_gateway/zai/glm-4.5v
    input_cost_per_token: 6.0e-07
    output_cost_per_token: 1.8e-06
- litellm_params:
    model: openrouter/z-ai/glm-4.6
    input_cost_per_token: 6.0e-07
    output_cost_per_token: 2.2e-06
  model_name: zai-glm-4.6
- model_name: zai-glm-4.6
  litellm_params:
    model: vercel_ai_gateway/zai/glm-4.6
    input_cost_per_token: 6.0e-07
    output_cost_per_token: 2.2e-06
